<?php

use Illuminate\Database\Seeder;

class PointsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void 
     */
    public function run()
    {
      DB::table('points')->truncate();
      DB::table('points')->insert([
        [
          'title'       => 'A casa nostra',
          'lng'         => '9.137445463100335',
          'lat'         => '45.46137836729994',
          'place_name'  => 'Bande Nere',
          'genre'       => 'Finzione',
          'year'        => '2006',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=47633',
          'director'    => 'Francesca Comencini',
          'actors'      => 'Valeria Golino, Luca Zingaretti, Laura Chiatti, Giuseppe Battiston',
          'video_link'  => 'http://www.youtube.com/watch?v=g0Ol5Sp42Po',
          'sinossi'     => 'Vari personaggi ci vengono mostrati raccontando il loro rapporto con il denaro e gli scambi che, più o meno consapevolmente, hanno tra di loro. Ugo è un affermato commercialista che si arricchisce riciclando denaro proveniente da attività illecite. Su di lui indaga Rita, una giovane comandante della Guardia di Finanza. E poi, come in un gioco di specchi, una modella, un uomo politico, una prostituta ucraina, una coppia di pensionati e, infine, un benzinaio.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Banditi a Milano',
          'lng'         => '9.183279050746819',
          'lat'         => '45.46942964627892',
          'place_name'  => 'Foro Bonaparte',
          'genre'       => 'Finzione',
          'year'        => '1968',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=21715',
          'director'    => 'Carlo Lizzani',
          'actors'      => 'Gian Maria Volontè, Don Backy, Ray Lovelock, Enzo Sancrotti, Piero Mazzarella',
          'video_link'  => 'http://www.youtube.com/embed/07Dw9Qkm3pQ',
          'sinossi'     => 'Quattro banditi, inseguiti dalla polizia dopo un colpo in banca, sparano sulla folla. Lizzani prende lo spunto da un fatto di cronaca e realizza un poliziesco pieno di suspense, ben fotografato e con qualche autentico pezzo di bravura (la fuga in automobile).',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Bingo Bongo',
          'lng'         => '9.195857100000012',
          'lat'         => '45.4647375',
          'place_name'  => 'Corso Vittorio Emanuele',
          'genre'       => 'Finzione',
          'year'        => '1983',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=16397',
          'director'    => 'Pasquale Festa Campanile',
          'actors'      => 'Adriano Celentano, Felice Andreasi, Carole Bouquet, Enzo Robutti',
          'video_link'  => 'http://youtu.be/-i4l6pxRZIY',
          'sinossi'     => 'Un bambino in fasce viene paracadutato in piena selva africana, sfuggendo ad un disastro aereo, cresce con le scimmie e molti anni dopo è raccolto e catturato da una spedizione scientifica che lo porta a Milano per ragioni di studio. Qui il giovanotto-scimmia che non sa parlare e agire da uomo, colloquia con gli animali e fa disperare del suo recupero "civile". Tutto questo non gli impedisce di innamorarsi d\'una bella antropologa, che si prende amorevole cura di lui.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Fame chimica',
          'lng'         => '9.154339700000037',
          'lat'         => '45.4363258',
          'place_name'  => 'Barona',
          'genre'       => 'Finzione',
          'year'        => '2003',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=43008',
          'director'    => 'Antonio Bocola, Paolo Vari',
          'actors'      => 'Marco Foschi, Matteo Gianoli, Valeria Solarino, Teco Celio',
          'video_link'  => 'http://www.youtube.com/watch?v=3T772M9hNR0',
          'sinossi'     => 'Due amici continuano a frequentarsi nella piazza dove si sono conosciuti da bambini, anche se le vite che conducono sono diverse: uno vive facendo il "pusher", mentre l\'altro ha un lavoro "normale", faticoso e sotto pagato. La profonda amicizia si incrina quando compare una bella ragazza di cui entrambi si innamorano.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Fuori dal mondo',
          'lng'         => '9.19967459999998',
          'lat'         => '45.4729995',
          'place_name'  => 'Parco di via Palestro',
          'genre'       => 'Finzione',
          'year'        => '1998',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=35828',
          'director'    => 'Giuseppe Piccioni',
          'actors'      => 'Silvio Orlando, Margherita Buy, Marina Massironi, Giuliana Lojodice',
          'video_link'  => 'http://www.youtube.com/watch?v=Y2UjZUp0P6Q',
          'sinossi'     => 'A Milano, oggi, Caterina, giovane suora prossima alla dichiarazione di professione perpetua, si vede affidare da un uomo di passaggio un neonato abbandonato nel parco. Caterina lo porta all\'ospedale ma non riesce a dimenticarlo, lo va a trovare e sente dentro di sé l\'urgenza di sapere qualche notizia in più.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Gli uomini... che mascalzoni!',
          'lng'         => '9.155231100000037',
          'lat'         => '45.4753664',
          'place_name'  => 'Fiera Campionaria',
          'genre'       => 'Finzione',
          'year'        => '1932',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=30828',
          'director'    => 'Mario Camerini',
          'actors'      => 'De Sica, Cesare Zoppetti, Lia Franca, Aldo Moschino',
          'video_link'  => 'http://www.youtube.com/watch?v=K0rzX3VJgeY',
          'sinossi'     => 'A Milano lo chauffeur Bruno si finge proprietario di un\'automobile per fare colpo su Mariuccia, commessa in una profumeria',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Cado dalle nubi',
          'lng'         => '9.203133442572039',
          'lat'         => '45.48447039656625',
          'place_name'  => 'Stazione Centrale',
          'genre'       => 'Comico',
          'year'        => '2009',
          'info_link'   => 'http://www.mymovies.it/film/2009/cadodallenubi/',
          'director'    => 'Gennaro Nunziante',
          'actors'      => 'Checco Zalone, Giulia Michelini, Dino Abbrescia',
          'video_link'  => 'http://youtu.be/JVHv0_W_Jqc',
          'sinossi'     => 'Checco vive in Puglia e coltiva il sogno di fare il musicista neomelodico ma la sua ragazza, Angela, non lo prende sul serio e, stanca del suo disimpegno, lo abbandona. Addolorato, Checco lascia Polignano a mare e va dal cugino a Milano. Qui conosce la bella Marika, figlia di un leghista convinto, alla quale sembra non interessare che come amico, buffone di corte. Affranto, Checco decide allora di tentare il provino per il programma "I want you", che seleziona talenti musicali per la tv.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Il disordine',
          'lng'         => '9.189729520762626',
          'lat'         => '45.46390902112502',
          'place_name'  => 'Piazza Duomo',
          'genre'       => 'Finzione',
          'year'        => '1962',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=9004',
          'director'    => 'Franco Brusati',
          'actors'      => 'Renato Salvatori, Curd Jürgens, Alida Valli, Jean Sorel, Louis Jourdan',
          'video_link'  => 'http://www.youtube.com/watch?v=Gw2WgfEIf9s',
          'sinossi'     => 'Lo sfondo è Milano, caotica e disordinata, dove il giovane protagonista, Mario, incontra l\'ironico ed egoista magnate dell\'industria, la signora capricciosa e gli snob tormentati, esseri a cui Mario disperatamente si aggrappa per risolvere il suo problema.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Il posto',
          'lng'         => '9.183019100000024',
          'lat'         => '45.47105699999999',
          'place_name'  => 'Foro Bonaparte',
          'genre'       => 'Finzione',
          'year'        => '1961',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=12516',
          'director'    => 'Ermanno Olmi',
          'actors'      => 'Bice Melegari, Mara Revel, Tullio Kezich, Loredana Detto, Sandro Panseri',
          'video_link'  => 'http://www.youtube.com/watch?v=rQF20NrsL_U',
          'sinossi'     => 'Nel pieno del boom economico dei primi anni sessanta, un ragazzo di Meda, Domenico, partecipa ad una selezione di lavoro presso una grande azienda di Milano. Vive questo impegno con particolare apprensione a causa della famiglia, che si aspetta da lui che riesca ad ottenere il posto fisso con cui sistemarsi per tutta la vita.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Il ragazzo di campagna',
          'lng'         => '9.197742500000004',
          'lat'         => '45.4665591',
          'place_name'  => 'San Babila',
          'genre'       => 'Finzione',
          'year'        => '1984',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=25506',
          'director'    => 'Franco Castellano, Pipolo',
          'actors'      => 'Renato Pozzetto, Massimo Boldi, Donna Osterbuhr, Massimo Serato',
          'video_link'  => 'http://www.youtube.com/watch?v=u_5ePOZsiq8',
          'sinossi'     => 'Artemio contadinotto scapolo, è svegliato dal gallo di buon mattino e inizia svogliato il solito lavoro in una campagna brulla e smisurata. Il paese - ai margini di una ferrovia secondaria - quasi non esiste e l\'unico svago dei pochi paesani è assistere al passaggio del treno. Inutilmente la madre propone all\'indolente e maturo "ragazzo" il matrimonio con Maria Rosa, una ragazzotta del paese sgraziata bruttina e con la faccia cosparsa di brufoli. Artemio, stufo di quelle giornate monotone decide di andare in città a cercarsi un\'occupazione più gratificante.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'La baraonda',
          'lng'         => '9.158434800000009',
          'lat'         => '45.48256360000001',
          'place_name'  => 'Vigorelli',
          'genre'       => 'Finzione',
          'year'        => '1980',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=15337',
          'director'    => 'Florestano Vancini',
          'actors'      => 'Giuliano Gemma, Edy Angelillo, Wanda Aschel Bacciella',
          'video_link'  => 'http://www.youtube.com/watch?v=_np_C5OC6Qc',
          'sinossi'     => 'Il racconto è tenuto insieme dal tenue filo che pare torni a legare Federico Salvi, un giovane medico sportivo di turno alla sei giorni ciclistica che si svolge al Palasport di Milano, ed Erminia, una ragazza romagnola che ha avuto con lui una fugace avventura amorosa.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'La vita agra',
          'lng'         => '9.201329028588816',
          'lat'         => '45.48457800738139',
          'place_name'  => 'Grattacielo Pirelli',
          'genre'       => 'Finzione',
          'year'        => '1964',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=10495',
          'director'    => 'Carlo Lizzani',
          'actors'      => 'Ugo Tognazzi, Giovanna Ralli, Giampiero Albertini, Rossana Martini',
          'video_link'  => 'http://www.youtube.com/watch?v=sUv7rOUkGxE',
          'sinossi'     => 'Addetto ai servizi culturali di una grande miniera, Luciano Bianchi viene licenziato. Per vendicare se stesso ed i minatori periti in una grave sciagura, Luciano si reca a Milano deciso a far saltare con la dinamite l\'imponente grattacielo dove ha sede la società mineraria',
          'city_id'     => '1',
        ],
        [
          'title'       => 'L\'aria serena dell\'ovest',
          'lng'         => '9.175309500000026',
          'lat'         => '45.4685189',
          'place_name'  => 'Stazione Cadorna',
          'genre'       => 'Finzione',
          'year'        => '1990',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=26519',
          'director'    => 'Silvio Soldini',
          'actors'      => 'Ivano Marescotti, Fabrizio Bentivoglio, Antonella Fattori, Barbara Valmorin',
          'video_link'  => 'http://www.youtube.com/watch?v=jqmXcaeP9EY',
          'sinossi'     => 'A Milano Veronica, un\'infermiera abituata ad avere molti amanti occasionali, uscendo un mattino dalla casa di Cesare Noviti, col quale ha trascorso la notte senza dirgli neppure il proprio nome, vi dimentica un\'agendina contenente nomi, indirizzi e numeri telefonici. Il giovanotto, che fa indagini di mercato per la Cosmos e che sta per essere trasferito in Svizzera, cerca di ritrovare la sconosciuta servendosi inutilmente dell\'agenda.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Gente dei navigli',
          'lng'         => '9.169091600000002',
          'lat'         => '45.4287895',
          'place_name'  => 'Navigli',
          'genre'       => 'Documentario',
          'year'        => '1960',
          'info_link'   => 'http://www.imdb.com/title/tt0347057/',
          'director'    => 'Guido Guerrasio',
          'actors'      => '',
          'video_link'  => 'http://www.youtube.com/watch?v=KvPMPEcvEl4',
          'sinossi'     => 'Uno sguardo documentaristico ai navigli milanesi e agli abitanti del quartiere.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'L\'audace colpo dei soliti ignoti',
          'lng'         => '9.202784699999938',
          'lat'         => '45.48484879999999',
          'place_name'  => 'Stazione Centrale',
          'genre'       => 'Finzione',
          'year'        => '1960',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=10530',
          'director'    => 'Nanni Loy',
          'actors'      => 'Nino Manfredi, Claudia Cardinale, Vittorio Gassman, Renato Salvatori',
          'video_link'  => 'http://www.youtube.com/watch?v=AyMOZkaJYCM',
          'sinossi'     => 'Peppe, capo di una combriccola di ladruncoli romani, viene avvicinato da un collega milanese, che lo invita a partecipare coi suoi ad un grosso colpo. Si tratta di bloccare il furgone che ogni domenica porta al sicuro le somme delle giocate incassate dal Totocalcio.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Lui è peggio di me',
          'lng'         => '9.17974300000003',
          'lat'         => '45.4492207',
          'place_name'  => 'San Gottardo',
          'genre'       => 'Finzione',
          'year'        => '1984',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=25288',
          'director'    => 'Enrico Oldoini',
          'actors'      => 'Renato Pozzetto, Adriano Celentano, Kelly Van Der Velden, Sergio Renda',
          'video_link'  => 'http://www.youtube.com/watch?v=992VoDGj4yo',
          'sinossi'     => 'Leonardo e Luciano sono comproprietari a Milano di un grosso "garage" dove si danno a noleggio belle e lussuose macchine d\'epoca. I due sono amici fraterni fin dalle elementari, vivono insieme, si scambiano allegramente frecciate e ragazze.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'L\'uomo perfetto',
          'lng'         => '8.722839099999987',
          'lat'         => '45.6313567',
          'place_name'  => 'Aeroporto di Malpensa',
          'genre'       => 'Finzione',
          'year'        => '2005',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=44426',
          'director'    => 'Luca Lucini',
          'actors'      => 'Francesca Inaudi, Riccardo Scamarcio, Gabriella Pession, Giampaolo Morelli',
          'video_link'  => 'http://www.youtube.com/watch?v=470S302Hdog',
          'sinossi'     => 'Una giovane e brillante pubblicitaria, Lucia, non può accettare che Maria, la sua migliore amica, stia organizzando il matrimonio con Paolo, l\'uomo da lei amato in segreto sin dai tempi di scuola. Lucia, che è combattiva e piena di fantasia, decide perciò di riconquistare il "suo" uomo.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Marrakech Express',
          'lng'         => '9.204702199999929',
          'lat'         => '45.4740353',
          'place_name'  => 'Planetario',
          'genre'       => 'Finzione',
          'year'        => '1989',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=25814',
          'director'    => 'Gabriele Salvatores',
          'actors'      => 'Fabrizio Bentivoglio, Diego Abatantuono, Cristina Marsillach, Giuseppe Cederna',
          'video_link'  => 'http://www.youtube.com/watch?v=-hMNyCbAL-0',
          'sinossi'     => 'In una sera piovosa il trentenne Marco si vede arrivare a casa una ragazza spagnola, Teresa, che gli racconta di essere la fidanzata di Rudy, un amico che non vede da dieci anni. Rudy è nei guai: si trova in Marocco dove è stato coinvolto in una storia di droga, e ha bisogno di 30 milioni di lire.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Ho fatto splash',
          'lng'         => '9.20559502976073',
          'lat'         => '45.4748015422991',
          'place_name'  => 'Corso Buenos Aires',
          'genre'       => 'Finzione',
          'year'        => '1980',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=14646',
          'director'    => 'Maurizio Nichetti',
          'actors'      => 'maurizio Nichetti, Angela Finocchiaro, Luisa Morandini, Carlina Torta',
          'video_link'  => 'http://www.youtube.com/watch?v=AOOxjC-uOi8',
          'sinossi'     => 'Nella casa milanese dove convivono Carlina, maestrina e promessa sposa, l\'aspirante attrice Luisa e la nullafacente Angela, alle prese con un bimbetto depositato da un\'amica in viaggio, arriva Maurizio, appena risvegliatosi da un sonno di 20 anni, causato dall\'ascolto di "Grazie dei fior", cantata da Nilla Pizzi.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Milano calibro 9',
          'lng'         => '9.169091600000002',
          'lat'         => '45.4287895',
          'place_name'  => 'Navigli',
          'genre'       => 'Finzione',
          'year'        => '1972',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=20915',
          'director'    => 'Fernando Di Leo',
          'actors'      => 'Gastone Moschin, Barbara Bouchet, Mario Adorf, Frank Wolff',
          'video_link'  => 'http://www.youtube.com/watch?v=IzPR4H3D_Sc',
          'sinossi'     => 'Uscito di prigione dopo tre anni scontati per una rapina, Ugo Piazza, già corriere di un trafficante di valuta, l\'Americano, viene aggredito e percosso a sangue dagli uomini di quest\'ultimo - guidati da Rocco, il suo braccio destro - che lo accusano d\'aver tenuto per sé 300 milioni di lire.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Filmati Lumière milanesi',
          'lng'         => '9.189777800524894',
          'lat'         => '45.46448089993574',
          'place_name'  => 'Piazza Duomo',
          'genre'       => 'Documentario',
          'year'        => '1896',
          'info_link'   => 'www.cinetecamilano.it',
          'director'    => 'Auguste e Louis Lumière',
          'actors'      => '',
          'video_link'  => 'http://www.youtube.com/watch?v=Z_SuPN7EHCU',
          'sinossi'     => 'Le prime riprese della piazza del Duomo girate dagli inventori del cinema.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Milano nera',
          'lng'         => '9.123252900000011',
          'lat'         => '45.4772731',
          'place_name'  => 'Stadio San Siro',
          'genre'       => 'Drammatico',
          'year'        => '1960',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=7758',
          'director'    => 'Gian Rocco e Pino Serpi',
          'actors'      => 'Alessandro Quasimodo, Adriano Fossati, Umberto Rocco, Sonia Gessner',
          'video_link'  => 'http://www.youtube.com/watch?v=Xh1E-qLaNR4',
          'sinossi'     => 'Il "Contessa", "Mosè", il "Gimkana", Toni detto "Elvis", "Rospo" che della banda di teddy boys è il capo, il suo fratellino Cino. Milano si ricostruisce. È tutta grattacieli, fabbriche, neon, juke-box, macerie e... Adriano Celentano. Una notte di capodanno di fine anni Cinquanta, in un turbinare di motociclette e macchine rubate, i ragazzi della ghenga festeggiano a modo loro...',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Miracolo a Milano',
          'lng'         => '9.188898035968009',
          'lat'         => '45.4638300110964',
          'place_name'  => 'Piazza Duomo',
          'genre'       => 'Drammatico',
          'year'        => '1951',
          'info_link'  => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=5143',
          'director'    => 'Vittorio De Sica',
          'actors'      => 'Paolo Stoppa, Alba Arnova, Emma Gramatica, Guglielmo Barnabò',
          'video_link'  => 'http://www.youtube.com/watch?v=CmEXxBeGSvY',
          'sinossi'     => 'Una buona vecchina, la signora Lolotta, trova un giorno sotto un cavolo un bel bambino, lo prende con sé e gli fa da mamma. Quando Lolotta muore, il bambino, Totò, viene ricoverato in un orfanotrofio. Ne esce giovinetto e il caso lo mette a contatto con un gruppo di poveri, accampati in una zona abbandonata della periferia milanese.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Ratataplan',
          'lng'         => '9.170052899999973',
          'lat'         => '45.452412',
          'place_name'  => 'Ponte di Porta Genova',
          'genre'       => 'Comico',
          'year'        => '1979',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=14645',
          'director'    => 'Maurizio Nichetti',
          'actors'      => 'Maurizio Nichetti, Angela Finocchiaro, Edi Angelillo, Lydia Biondi',
          'video_link'  => 'http://www.youtube.com/watch?v=6etp3wYqHLg',
          'sinossi'     => 'Neolaureato, l\'ingegnere Colombo si presenta ad un concorso dove, essendo l\'unico che ha realizzato un test valido, non viene assunto. Allora si dà da fare come inserviente barista e attraversa l\'intera città di Milano per portare un bicchiere d\'acqua al moribondo presidente di una assemblea industriale. L\'acqua, corrotta per cento avventure, diviene miracolosa e, di conseguenza, al bar accorrono impediti di ogni genere che guariscono.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Rinascente',
          'lng'         => '9.193620137681592',
          'lat'         => '45.46491432896893',
          'place_name'  => 'La Rinascente - Corso Vittorio Emanuele II',
          'genre'       => 'Documentario',
          'year'        => '1920',
          'info_link'   => 'www.cinetecamilano.it',
          'director'    => '',
          'actors'      => '',
          'video_link'  => 'http://www.youtube.com/watch?v=RCnY9QqLdNI',
          'sinossi'     => 'Immagini d\'epoca dei grandi magazzini milanesi.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Rocco e i suoi fratelli',
          'lng'         => '9.20354268456424',
          'lat'         => '45.485947007370925',
          'place_name'  => 'Stazione Centrale',
          'genre'       => 'Drammatico',
          'year'        => '1960',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=11619',
          'director'    => 'Luchino Visconti',
          'actors'      => 'Claudia Cardinale, Alain Delon, Roger Hanin, Katina Paxinou',
          'video_link'  => 'http://youtu.be/uAAU5Fb9ZGs',
          'sinossi'     => 'Una povera vedova, Rosaria, lascia in treno con i suoi quattro figlioli il paese della Lucania in cui è nata, per trasferirsi a Milano, dove vive il figlio maggiore, Vincenzo. Questi non può fare molto per la famiglia, ma riesce ad introdurre i fratelli nel mondo del pugilngo.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Romanzo popolare',
          'lng'         => '9.179740700000025',
          'lat'         => '45.4525515',
          'place_name'  => 'Darsena',
          'genre'       => 'Commedia',
          'year'        => '1974',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=13812',
          'director'    => 'Mario Monicelli',
          'actors'      => 'Ugo Tognazzi, Michele Placido, Ornella Muti, Pippo Starnazza',
          'video_link'  => 'http://www.youtube.com/watch?v=-4ZQJkKVMrk',
          'sinossi'     => 'L\'attempato e scapolo operaio milanese Giulio Basletti sposa Vincenzina Rotunno, la figlioccia che ha tenuto a battesimo 18 anni prima nel corso di una fugace trasferta a Montecagnano, in provincia di Avellino.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Cronaca di un amore',
          'lng'         => '9.290858161484493',
          'lat'         => '45.46544885193326',
          'place_name'  => 'Idroscalo',
          'genre'       => 'Drammatico',
          'year'        => '1950',
          'info_link'   => 'http://it.wikipedia.org/wiki/Cronaca_di_un_amore',
          'director'    => 'Michelangelo Antonioni',
          'actors'      => 'Massimo Girotti, Lucia Bosè',
          'video_link'  => 'http://youtu.be/_m1WJXTy_Ag',
          'sinossi'     => 'Enrico, vittima di una immotivata gelosia nei confronti del passato sentimentale della moglie Paola, assolda un investigatore per capire se gli è fedele. Questo atteggiamento spinge paola tra le braccia di Guido, uomo di cui era innamorata in passato. Inevitabilmente tra i due scoppia una pericolosa e travolgente passione.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Totò, Peppino e la malafemmina',
          'lng'         => '9.18960613914794',
          'lat'         => '45.464131001089115',
          'place_name'  => 'Piazza Duomo',
          'genre'       => 'Comico',
          'year'        => '1956',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=10742',
          'director'    => 'Camillo Mastrocinque',
          'actors'      => 'Totò, Peppino De Filippo, Vittoria Crispo, Dorian Gray, Teddy Reno, Nino Manfredi.',
          'video_link'  => 'http://www.youtube.com/watch?v=Vhe4MHY9UYc',
          'sinossi'     => '',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Un povero ricco',
          'lng'         => '9.175086100000044',
          'lat'         => '45.4125968',
          'place_name'  => 'Via dei Missaglia',
          'genre'       => 'Commedia',
          'year'        => '1983',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=16398',
          'director'    => 'Pasquale Festa Campanile',
          'actors'      => 'Renato Pozzetto, Ornella Muti, Piero Mazzarella, Corrado Olmi',
          'video_link'  => 'http://www.youtube.com/watch?v=OgARb8BJ3ng',
          'sinossi'     => 'Eugenio è un industriale quarantenne ossessionato dall\'incubo del crack finanziario. Poiché i suoi incubi gli impediscono di essere sereno, ricorre ad uno psicologo, il quale gli consiglia di "allenarsi" a fare il povero, per riuscire a ritrovare se stesso.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Via Montenapoleone',
          'lng'         => '9.278851651898208',
          'lat'         => '45.46120984646536',
          'place_name'  => 'Aeroporto Linate',
          'genre'       => 'Commedia',
          'year'        => '1986',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=26041',
          'director'    => 'Carlo Vanzina',
          'actors'      => 'Valentina Cortese, Luca Barbareschi, Renée Simonsen, Valeria Cavalli',
          'video_link'  => 'http://www.youtube.com/watch?NR=1&v=siDJ0YUtFG8',
          'sinossi'     => 'Passano spesso per Via Montenapoleone i personaggi di questa storia, che è storia di piccole vicende, di amare esperienze, di incontri e di abbandoni e di non poche sciocchezze. Alcune si intrecciano, altre avranno un seguito.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'La notte',
          'lng'         => '9.213333721765139',
          'lat'         => '45.53138833857003',
          'place_name'  => 'Parco Nord',
          'genre'       => 'Finzione',
          'year'        => '1961',
          'info_link'   => 'http://it.wikipedia.org/wiki/La_notte_(film_1961)',
          'director'    => 'Michelangelo Antonioni',
          'actors'      => 'Monica Vitti, Marcello Mastroianni, Jeanne Moreau',
          'video_link'  => 'http://www.youtube.com/watch?v=OJYQE7bcQh8',
          'sinossi'     => 'Lento sfaldarsi dei rapporti affettivi tra lo scrittore Giovanni Pontano e la moglie Lidia. La crisi si consuma tra la visita a un amico moribondo in clinica e la noia di una festa mondana. Si scivola nel disamore. L\'azione si svolge a Milano da un pomeriggio di sabato all\'alba di domenica.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Anna',
          'lng'         => '9.195057499999962',
          'lat'         => '45.5077017',
          'place_name'  => 'Ospedale Niguarda Cà Granda',
          'genre'       => 'Drammatico',
          'year'        => '1951',
          'info_link'   => 'http://it.wikipedia.org/wiki/Anna_(film_1951)',
          'director'    => 'Alberto Lattuada',
          'actors'      => 'Silvana Mangano, Ralf Vallone, Vittorio Gassman',
          'video_link'  => 'http://www.youtube.com/watch?v=KIEUFeONjK0',
          'sinossi'     => 'Una suora lavora in un ospedale come infermiera. Durante il film si scopre la sua vita precedente come cantante e ballerina di night club e le ragioni che la hanno portata alla nuova scelta di vita.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Bubù',
          'lng'         => '9.156738865606712',
          'lat'         => '45.44803547008363',
          'place_name'  => 'Alzaia Naviglio Grande',
          'genre'       => 'Drammatico',
          'year'        => '1971',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=18866',
          'director'    => 'Mauro Bolognini',
          'actors'      => 'Massimo Ranieri, Ottavia Piccolo, Gigi Proietti',
          'video_link'  => 'http://youtu.be/n0vi2ADdHlI',
          'sinossi'     => 'Un fornaio decide per avere un\'entrata mensile più sostanziosa di cambiare lavoro. Spinge così la sua ragazza a prostituirsi divenendo suo protettore. La giovane cerca in tutti i modi di cambiare vita ma il giro malavitoso in cui è entrata non lascia scampo.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'La banda dei Babbi Natale',
          'lng'         => '9.188691880950955',
          'lat'         => '45.48676631594669',
          'place_name'  => 'Via Borsieri - Cavalcavia Eugenio Bussa',
          'genre'       => 'Comico',
          'year'        => '2010',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=53167',
          'director'    => 'Paolo Genovese',
          'actors'      => 'Aldo, Giovanni e Giacomo, Angela Finocchiaro',
          'video_link'  => 'http://youtu.be/k1xht2vcq2o',
          'sinossi'     => 'Vigilia di Natale. Tre amici uniti dalla passione delle bocce, sono finiti in questura perché accusati di essere una banda di ladri. L\'interrogatorio con una severa e materna ispettrice di Polizia è lo spunto per raccontare le loro vite complicate e per cercare il modo in cui vorrebbero cambiarle o almeno semplificarle. Riusciranno a dimostrare la loro innocenza entro la mezzanotte?',
          'city_id'     => '1',
        ],
        [
          'title'       => 'I cannibali',
          'lng'         => '9.216846499999974',
          'lat'         => '45.4587033',
          'place_name'  => 'Largo Marinai d\'Italia',
          'genre'       => 'Drammatico',
          'year'        => '1969',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=20269',
          'director'    => 'Liliana Cavani',
          'actors'      => 'Tomas Milian, Pierre Clementi, Britt Ekland',
          'video_link'  => 'http://youtu.be/QTlvjaUUcJo',
          'sinossi'     => 'Un regime totalitario fa sì che le strade di una grande città siano piene di cadaveri dei ribelli. Tali corpi sono un monito per chi vuole opporsi e non devono essere toccati, pena la morte, per ordine supremo. Antigone vorrebbe seppellire il proprio fratello, trova aiuto in un misterioso straniero che parla una lingua sconosciuta.La donna e lo straniero sono arrestati e torturati. Riescono a fuggire ma sono uccisi dalla polizia. Diventano però un simbolo per tanti giovani che, da quel momento, iniziano a prendere i cadaveri dei ribelli per seppellirli.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Io sono l\'amore',
          'lng'         => '9.176910507934508',
          'lat'         => '45.46818702957662',
          'place_name'  => 'Stazione Cadorna',
          'genre'       => 'Drammatico',
          'year'        => '2009',
          'info_link'   => 'http://it.wikipedia.org/wiki/Io_sono_l\'amore',
          'director'    => 'Luca Guadagnino',
          'actors'      => 'Tilda Swinton, Flavio Parenti, Alba Rohrwacher, Pippo Delbono',
          'video_link'  => 'http://youtu.be/dzK3rW5y5BY',
          'sinossi'     => 'Film incentrato sulle vicende della ricca famiglia lombarda dei Recchi, composta da Emma e Tancredi e dai loro figli Elisabetta, Edoardo e Gianluca. Tra riti borghesi e convenzioni sociali, si consumano le storie dei vari membri della famiglia. L\'algida Emma troverà conforto e amore tra le braccia del giovane cuoco, Antonio. La passione che scoppia i due romperà legami e convenzioni ben radicate.',
          'city_id'     => '1',
        ],
        [
          'title'       => 'Lo svitato',
          'lng'         => '9.179489729638703',
          'lat'         => '45.47556595716807',
          'place_name'  => 'Arena Civica',
          'genre'       => 'Finzione',
          'year'        => '1956',
          'info_link'   => 'http://www.cinematografo.it/pls/cinematografo/consultazione.redirect?sch=10488',
          'director'    => 'Carlo Lizzani',
          'actors'      => 'Dario Fo, Franca Rame',
          'video_link'  => 'http://youtu.be/Aa6OakOIVWY',
          'sinossi'     => 'Achille, fattorino nella redazione di un giornale milanese della sera, è preso per un giornalista e riesce a mettere insieme un articolo sportivo-sentimentale, che in giorno di magra viene pubblicato dal giornale. Ha poi l\'occasione di fare un reportage fotografico ed un\'intervista col mostro della via Emilia, che gli fruttano una gratifica ed un elogio da parte del direttore. Nel frattempo la conosciuto Gigi, un maneggione, il quale ha visto subito quale partito egli possa trarre dalle velleità giornalistiche e dall\'ingenuità di Achille. Egli induce quest\'ultimo a preparare insieme a lui un furto in grande stile, per essere poi il primo a darne la notizia sul giornale. Si tratta di rubare dei cani di razza di gran valore esposti in una mostra, sostituendoli con cani bastardi. In realtà Gigi si è proposto di rubare i cani per davvero, approfittando dell\'ingenuità d\'Achille; ma in seguito ad un incidente, le cose prendono un\'altra piega. I cani vengono prelevati, ma poi fuggono e sono involontariamente scambiati con i bastardi. Così il colpo giornalistico è sfumato: Gigi però approfitta dell\'occasione per portarsi via Elena, la ragazza della quale Achille era innamorato. Il povero Achille riprende la sua grama vita: egli troverà conforto nell\'amore di Diana, l\'ex amica di Gigi, che gli dimostra un\'affettuosa simpatia.',
          'city_id'     => '1',
        ]
        // [
        //   'title'       => '',
        //   'lng'         => '',
        //   'lat'         => '',
        //   'place_name'  => '',
        //   'genre'       => '',
        //   'year'        => '',
        //   'info_link'   => '',
        //   'director'    => '',
        //   'actors'      => '',
        //   'video_link'  => '',
        //   'sinossi'     => '',
        //   'city_id'     => '',
        // ],
      ]);
    }
}
