INSERT INTO `tfc_schools` (`id`, `name`, `created_at`, `updated_at`, `country`)
VALUES
    (NULL, 'IIS S. Caterina da Siena, Milano', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Artistico di Latina, Latina', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Candiani, Busto Arstizio', NULL, NULL, 'Italy'),
    (NULL, 'IC Massa, Milano', NULL, NULL, 'Italy'),
    (NULL, 'IIS Volta-Fellini, Riccione', NULL, NULL, 'Italy'),
    (NULL, 'Istituto Onnicomprensivo di Orte, Orte', NULL, NULL, 'Italy'),
    (NULL, 'Istituto Leardi, Alessandria	"', NULL, NULL, 'Italy'),
    (NULL, 'IC Portalurago, Erba (CO)"', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Scientifico Morgagni, Roma', NULL, NULL, 'Italy'),
    (NULL, 'IC Castegnato, Brescia', NULL, NULL, 'Italy'),
    (NULL, 'IPS Pantaleoni, Frascati', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Labriola, Ostia', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Scientifico Cavour, Roma', NULL, NULL, 'Italy'),
    (NULL, 'IC piazzale della gioventù, S. Marinella (RM)"', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Scientifico Gullace, Roma', NULL, NULL, 'Italy'),
    (NULL, 'IPS Cosmai, Trani', NULL, NULL, 'Italy'),
    (NULL, 'IC Franceschi, Milano', NULL, NULL, 'Italy'),
    (NULL, 'IIS Midossi, Civita Castellana (VT)"', NULL, NULL, 'Italy'),
    (NULL, 'IPS Calzecchi onesti, Ancona', NULL, NULL, 'Italy'),
    (NULL, 'Liceo Keplero, Roma', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2B della Scuola Secondaria di Primo Grado D. Buzzati, Milano (MI) – Prof.ssa Musolino', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2A della Scuola Secondaria di Primo Grado Tommaseo, Milano (MI) – Prof. Carlucci', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3D dell’ITSOS Albe Steiner, Milano (MI) – Prof.ssa Arcangeletti', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3IR dell’Istituto di Istruzione Secondaria Superiore R. Luxemburg, Milano (MI) – Prof.ssa De Meo', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2E della Scuola Secondaria di Primo Grado Salvador Allende, Paderno Dugnano (MI) – Prof.ssa Alessandrini', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3E della Scuola Secondaria di Primo Grado Salvador Allende, Paderno Dugnano (MI) – Prof.ssa Lo Cascio', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2C della Scuola Secondaria di Primo Grado Salvador Allende, Paderno Dugnano (MI) – Prof.ssa Bazzocchi', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2B della Scuola Secondaria di Primo Grado Salvador Allende, Paderno Dugnano (MI) – Prof.ssa Celi', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2D della Scuola Secondaria di Primo Grado T. Croci, Paderno Dugnano (MI) – Prof.ssa Doriguzzi', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2C della Scuola Secondaria di Primo Grado T. Croci, Paderno Dugnano (MI) – Prof.ssa Restelli', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2B della Scuola Secondaria di Primo Grado Breda, Sesto San Giovanni (MI) – Prof.ssa Mattei', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2D della Scuola Secondaria di Primo Grado Bellani, Monza (MB)– Prof.ssa Cascina', NULL, NULL, 'Italy'),
    (NULL, 'Classe 2F dell’I.I.S. Podesti Calzecchi Onesti, Ancona (AN) – Prof.ssa Gregorini', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3V1 del Liceo Artistico P. Candiani, Busto Arsizio (VA) - Prof.ssa Madonia', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3V2 del Liceo Artistico P. Candiani, Busto Arsizio (VA)- Prof. Cunocchiella', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3A dell’IIS Via Sarandì, Roma – Prof. Campogiani e Prof.ssa Maffi', NULL, NULL, 'Italy'),
    (NULL, 'Classe 3B dell’IIS Via Sarandì, Roma – Prof. Campogiani e Prof.ssa Maffi', NULL, NULL, 'Italy'),
    (NULL, 'Lisneal College - Derry', NULL, NULL, 'Northern Ireland'),
    (NULL, 'Foyle College - Derry', NULL, NULL, 'Northern Ireland'),
    (NULL, 'Oakgrove Integrated College - Derry', NULL, NULL, 'Northern Ireland'),
    (NULL, 'St Cecilia\'s College - Derry', NULL, NULL, 'Northern Ireland'),
    (NULL, 'St Joseph\'s College - Derry', NULL, NULL, 'Northern Ireland'),
    (NULL, 'Elementary school “Stevan Sindjelic“, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'Elementary school “Jovan Popovic“, Indjija', NULL, NULL, 'Serbia'),
    (NULL, 'Elementary school “Dositej Obradovic“, Pozarevac', NULL, NULL, 'Serbia'),
    (NULL, 'Elementary school “Sveti Sava“, Mladenovac', NULL, NULL, 'Serbia'),
    (NULL, 'Secondary school Contemporary Gymnasium, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'Secondary school for Design, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'Artmedia School, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'Contemporary Gymnasium, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'ITHS - Contemporary Gymnasium, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'School for Design, Belgrade', NULL, NULL, 'Serbia'),
    (NULL, 'Tanfield School, UK', NULL, NULL, 'UK'),
    (NULL, 'Uppper Shirley High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Millfield School, UK', NULL, NULL, 'UK'),
    (NULL, 'ST.Peter’s School Solihull, UK', NULL, NULL, 'UK'),
    (NULL, 'Hartismere School, UK', NULL, NULL, 'UK'),
    (NULL, 'Southend High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Holy Cross School, UK', NULL, NULL, 'UK'),
    (NULL, 'Alperton High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Comberton Village College, UK', NULL, NULL, 'UK'),
    (NULL, 'Marple Hall, UK', NULL, NULL, 'UK'),
    (NULL, 'Long Road 6th Form College, UK', NULL, NULL, 'UK'),
    (NULL, 'Sackville School, UK', NULL, NULL, 'UK'),
    (NULL, 'Chipping Camden School, UK', NULL, NULL, 'UK'),
    (NULL, 'Causeway School, UK', NULL, NULL, 'UK'),
    (NULL, 'Altwood School, UK', NULL, NULL, 'UK'),
    (NULL, 'Friedslands School, UK', NULL, NULL, 'UK'),
    (NULL, 'Milbourne Lodge School, UK', NULL, NULL, 'UK'),
    (NULL, 'Liverpool College, UK', NULL, NULL, 'UK'),
    (NULL, 'Brooklands Shool, UK', NULL, NULL, 'UK'),
    (NULL, 'Homefield Prep School, UK', NULL, NULL, 'UK'),
    (NULL, 'Uxbridge College, UK', NULL, NULL, 'UK'),
    (NULL, 'Sedgehill School, UK', NULL, NULL, 'UK'),
    (NULL, 'Auchenharvie Academy, UK', NULL, NULL, 'UK'),
    (NULL, 'American Academy, UK', NULL, NULL, 'UK'),
    (NULL, 'Hereford College, UK', NULL, NULL, 'UK'),
    (NULL, 'Bournemouth University, UK', NULL, NULL, 'UK'),
    (NULL, 'Rickmansworth High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Brighton College, UK', NULL, NULL, 'UK'),
    (NULL, 'Mayfield School, UK', NULL, NULL, 'UK'),
    (NULL, 'Heathmount School, UK', NULL, NULL, 'UK'),
    (NULL, 'Norwood School, UK', NULL, NULL, 'UK'),
    (NULL, 'Byram Hills, UK', NULL, NULL, 'UK'),
    (NULL, 'The Oaks Secondary School, UK', NULL, NULL, 'UK'),
    (NULL, 'St Mary’s School, UK', NULL, NULL, 'UK'),
    (NULL, 'Whakatane High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Windsor Forrest Academy, UK', NULL, NULL, 'UK'),
    (NULL, 'Kings College, UK', NULL, NULL, 'UK'),
    (NULL, 'Ludlow College, UK', NULL, NULL, 'UK'),
    (NULL, 'Queen Ann’e High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Uxbridge College, UK', NULL, NULL, 'UK'),
    (NULL, 'Taylor High School, UK', NULL, NULL, 'UK'),
    (NULL, 'Thomas Star Middle School, UK', NULL, NULL, 'UK'),
    (NULL, 'Our Lady\'s Grammar School, UK', NULL, NULL, 'UK'),
    (NULL, 'Gosden House School, Horsham Road, Guildford GU5 0AH', NULL, NULL, 'UK'),
    (NULL, 'Congleton High School, Box Lane, Congleton, Cheshire, CW12 4NS', NULL, NULL, 'UK'),
    (NULL, 'Liverpool College, Queens DriveLiverpool, L18 8BG', NULL, NULL, 'UK'),
    (NULL, 'Glenthorne High School, 270 Sutton Common Road, Sutton SM3 9PS', NULL, NULL, 'UK'),
    (NULL, 'Valley Road School, 26 Valley Road, Henley On Thames, RG9 1RR', NULL, NULL, 'UK'),
    (NULL, 'University College London, Institute of Education', NULL, NULL, 'UK'),
    (NULL, 'Alleyns School, Townley Road, London SE22 8SU', NULL, NULL, 'UK'),
    (NULL, 'Scottish Scree Education', NULL, NULL, 'UK'),
    (NULL, 'Association of Media Educators, Scotland', NULL, NULL, 'UK'),
    (NULL, 'Village Kvemo Bodbi Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N51, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N145, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Kvenobni Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Zugdidi Public School N4, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Sachkhere N2 Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N71, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Abkhazian Public School N10, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Patardzeuli Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N146, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Kutaisi Public School N30, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Kutaisi Public School N17, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Kutaisi Public School N15, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Zestaponi Public School N7, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Chkhari Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Batumi Public School N20, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N169, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Gori Public School N13, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Gori Public School N11, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Gegelidzeebi Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Gori Public School N9, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Vilige Zvare public school, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Fari Public school, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N87, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N210, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N175, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Small town Surami Public School N2, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N124, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Naqalaqevi Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Kaspi Public School N11, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tbilisi Public School N182, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Rustavi Public School N6, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Rustavi Public School N28, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Secular Gymnasium "Shavnabada", KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Muskhi Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Village Tokhliauri Public School, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Dusheti Public School N2, KA', NULL, NULL, 'Georgia'),
    (NULL, 'Tsalka Public School N1, KA', NULL, NULL, 'Georgia'),
    (NULL, 'OŠ Koper, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Umetniška gimnazija, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Dragomirja Benčiča-Brkina, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Rudija Mahniča-Brkinca, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Šturje, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Prežihovega Voranca, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Franceta Bevka, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Bršljin, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Milana Jarca, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Elektro in računalniška šola, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ 8 talcev, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Vič, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Koroška bela, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'SŠ Slovenj Gradec, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Lucija, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Toneta Pavčka, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'dvojezična OŠ Lendava, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Gimnazija Antonio Sema, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Mislinja, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Dornberk, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Srednja tehniška šola, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Vojke Šmuc, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Gimnazija Celje - Center, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Gimnazija Franca Miklošiča, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Gimnazija Ormož, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Gimnazija Nova Gorica, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Zreče, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Košana in OŠ Prestranek, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Košana, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Prestranek, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Brezno-Podvelka, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Gimnazija Novo mesto, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Vodmat, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'Konservatorij za glasbo in balet, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Sava Kladnika, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Horjul, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Šmartno v Tuhinju, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Antona Globočnika, SI', NULL, NULL, 'Slovenia'),
    (NULL, 'OŠ Jožeta Moškriča, SI', NULL, NULL, 'Slovenia');